name: Build Pull Request
on:
  pull_request:
concurrency:
  group: build-pr-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  build-pr:
    name: Build Pull-Request
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
